# We define the services (containers) our app needs. For now, just one.
services:
  # We'll name our service 'backend'
  backend:
    # Build the container image from the Dockerfile in the current directory (.)
    build: 
      context: ./backend
    # Map port 3000 on our Mac to port 3000 inside the container
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    volumes:
    # create a sync between a 'vector_store' folder locally and the /app/vector_store' folder inside the container
      - ./vector_store:/app/vector_store
    container_name: documentor_backend
  
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:80"
    container_name: documentor_frontend
    depends_on:
      - backend

volumes:
  vector_store: