# We define the services (containers) our app needs. For now, just one.
services:
  # We'll name our service 'backend'
  backend:
    # Build the container image from the Dockerfile in the current directory (.)
    build: .
    # Map port 3000 on our Mac to port 3000 inside the container
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
    # create a sync between a 'vector_store' folder locally and the /app/vector_store' folder inside the container
      - ./vector_store:/app/vector_store